---
awx_namespace: "awx"
awx_helm_chart_version: "3.4.2"
awx_version: "17.1.0"
awx_ingress_domain: "awx.{{ ingress_domain }}"
awx_secret_key_secret_name: "awx-secret-key"
awx_admin_creds_secret_name: "awx-admin-creds"
awx_postgres_password: "dynatrace"
awx_default_org_name: "Default"
awx_admin_user : "dynatrace"
awx_admin_password : "dynatrace"
